# https://github.com/actions/labeler
name: Pull Request Labeler
permissions:
  contents: write
  issues: write
on:
  - pull_request_target
jobs:
  triage:
    if: github.repository == 'jrmatherly/DocsGPT'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
